// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type { BytesLike } from "dedot/codecs";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   *
   * @param {BytesLike} title
   * @param {BytesLike} description
   * @param {number} maxStudents
   * @param {bigint} startTime
   * @param {bigint} endTime
   * @param {bigint} price
   * @param {BytesLike} metadataHash
   * @param {ContractTxOptions} options
   *
   * @selector 0xc75902bc
   **/
  createCourse: GenericContractTxCall<
    ChainApi,
    (
      title: BytesLike,
      description: BytesLike,
      maxStudents: number,
      startTime: bigint,
      endTime: bigint,
      price: bigint,
      metadataHash: BytesLike,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;

  /**
   *
   * @param {number} courseId
   * @param {ContractTxOptions} options
   *
   * @selector 0x8c18306a
   **/
  enroll: GenericContractTxCall<
    ChainApi,
    (
      courseId: number,
      options: ContractTxOptions,
    ) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
