// Generated by dedot cli

import type { AccountId32, Bytes } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type ContractsEduverseCourse = {
  id: number;
  teacher: AccountId32;
  title: Bytes;
  description: Bytes;
  maxStudents: number;
  enrolledCount: number;
  startTime: bigint;
  endTime: bigint;
  price: bigint;
  active: boolean;
  metadataHash: Bytes;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type ContractsEduverse = {
  courseCounter: number;
  courses: InkStorageLazyMapping;
  studentEnrollments: InkStorageLazyMapping;
  teacherCourses: InkStorageLazyMapping;
  courseStudents: InkStorageLazyMapping;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type ContractsEduverseError =
  | "CourseNotFound"
  | "CourseIsFull"
  | "AlreadyEnrolled"
  | "NotEnrolled"
  | "InsufficientPayment"
  | "Unauthorized"
  | "CourseNotActive"
  | "InvalidTime";

export type InkEnvNoChainExtension = null;
